import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import { ThemeProvider } from "@/components/ThemeProvider";
import Navswitch from "@/components/Navbars/Navswitch";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type RootLayoutPropsType = Readonly<{
	children: ReactNode;
}>;

export default function RootLayout({ children }: RootLayoutPropsType) {
	return (
		<html
			lang="en"
			suppressHydrationWarning>
			<body>
				<ThemeProvider
					attribute="class"
					defaultTheme="light"
					enableSystem
					disableTransitionOnChange>
					<header className="border-b border-gray-700">
						<Navswitch />
					</header>
					<main className="container mx-auto px-8 md:px-32">
						{children}
					</main>
					<footer>
						<Footer />
					</footer>
				</ThemeProvider>
			</body>
		</html>
	);
}
